pdf:
  autoredeploy: true
  environment:
    - WEAVER_ATHENA_CMD=athenapdf -S --no-portrait -M none
    - WEAVER_AUTH_KEY=key
    - WEAVER_CONVERSION_FALLBACK=false
    - WEAVER_MAX_CONVERSION_QUEUE=100
    - WEAVER_MAX_WORKERS=1
    - WEAVER_WORKER_TIMEOUT=600
  image: 'arachnysdocker/athenapdf-service:latest'
  mem_limit: 192m
  ports:
    - '8080:8080'
  restart: always
  tags:
    - pdf